#!/bin/bash

# Author: Khaled Benfajria
# Date:   29-01-2023
# Name:   Installing MongoDB & MongoDB GUI powered by PHP

#######################################
# Print a message in a given color.
# Arguments:
#   Color. eg: green, red
#######################################
function print_color(){
  NC='\033[0m' # No Color

  case $1 in
    "green") COLOR='\033[1;32m' ;;
    "red") COLOR='\033[1;31m' ;;
    "yellow") COLOR='\033[1;33m' ;;
	"blue") COLOR='\033[1;34m' ;;
  esac

  echo -e "${COLOR} $2 ${NC}"
}

print_color "red" 'Before running the script, make sure your user in the www-data group.'
print_color "red" 'This action require you to logout and login again.'
print_color "blue" 'sudo usermod -a -G www-data $USER'

sleep 10

echo 

print_color "yellow" '--------------------------MongoDB & MongoDB GUI powered by PHP--------------------------------'

echo
# Installing MongoDB

print_color "green" '-----Installing MongoDB-----'
sudo apt-get update
sudo apt-get install ca-certificates -y
sudo apt-get install gnupg -y 
sudo wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
sudo echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo systemctl start mongod

# Installing apache2 & Activate rewrite module
# AllowOverride All in your Apache (virtual host) configuration.

print_color "green" '-----Installing apache2 & Activate rewrite module-----'
sudo apt-get install apache2 -y
sudo systemctl start apache2
sudo systemctl enable apache2
sudo a2enmod rewrite
sudo sed -i 's/None/All/g' /etc/apache2/apache2.conf
sudo sed -i 's+/var/www/html+/var/www/html/MongoDB-PHP-GUI+g' /etc/apache2/sites-enabled/000-default.conf
sudo systemctl relaod apache2 

# Installing php7.4 and Additional Dependencies

print_color "green" '-----Installing php7.4 and Additional Dependencies-----'
sudo apt-get install php libapache2-mod-php -y
sudo apt-get install php7.4-dev -y
sudo apt-get install php-pear -y
sudo pecl install mongodb-1.13.0
sudo apt-get install php7.4-mongodb -y

# Configuration MongoDB GUI

# Clone Mongo-php-GUI repository

print_color "-----green" '-----Configuration MongoDB GUI-----'
print_color "blue" '-----Clone Mongo-php-GUI repository-----'
sudo apt-get install git -y
cd /var/www/html/ && sudo git clone https://github.com/Khaled-Benfajria/MongoDB-PHP-GUI.git
sudo rm index.html && cd /var/www/html/MongoDB-PHP-GUI

# Downloading and Installing Composer

print_color "green" '-----Downloading and Installing Composer-----'
curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
echo $HASH
php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Do not use composer with sudo

sudo chown root:root /var/www
sudo chmod 755 /var/www/
sudo chown -R www-data:www-data /var/www/html/MongoDB-PHP-GUI
sudo chmod -R 774 /var/www/html/MongoDB-PHP-GUI

# Run composer install at project's root directory to install all PHP dependencies.

print_color "green" '-----Run composer install-----'
composer install --ignore-platform-req=ext-mongodb
sudo systemctl restart apache2 
